# dubplate version: v0.9.1

workspace:

  base: /go/src
  path: github.com/glynternet/etcd-osc-gateway


pipeline:

  run-unit-tests:
    image: golang:1.15.4
    commands:
      - go test -v -race ./...

  # drone mounts the root directory of the repository to the container and sets
  # it as the working directory
  run-linters:
    image: golangci/golangci-lint:v1.32.2-alpine
    commands:
      - golangci-lint run -v

  build-binaries:
    image: golang:1.15.4
    commands:
      - make binaries

  # images are not yet supported
  # build-images:
    # image: HMMMMMMMMM
    # environment:
      # - DOCKER_USERNAME=
