// Code generated by dubplate v0.15.0 DO NOT EDIT.
// This etcd-osc-gateway is the plain-label test pressing of the application.
// Implement the following function to use this boilerplate
// func buildCmdTree(logger log.Logger, out io.Writer, rootCmd *cobra.Command) {}

package main

import dubplate "github.com/glynternet/dubplate/app"

const appName = "etcd-osc-gateway"

// to be changed using ldflags with the go build command
var version = "unknown"

func main() {
	dubplate.App(appName, version, buildCmdTree)
}
